name: postman-api-CRUD-tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: https://registry.npmjs.org/
    - name: Install newman
      run: npm install -g newman
    - name: Run newman tests
      run: newman run "./APItests/Pet Shop- Pet CRUD tests.postman_collection.json"
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: postman-results
        path: results
        retention-days: 30
